### ISSUE TITLE
Make <SidePanel/> list background and images more dynamic

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#19]
@brenoc This is too brittle. Ideal setup would have:

 - [ ] One `prop` for each nav item in the markup, defining the icon for that item as an `<img/>` tag
 - [ ] A LESS function that changes the background color without the need for lots of `nth-child`

---

Files: 

`/src/styles/MobileSidePanel.less`
`/src/styles/DesktopSidePanel.less`

```less

.v-editor__sidepanel__item:nth-child(n+2) {
  background: url(/assets/@vtex.storefront-editor/icons/navigation-icon.svg) no-repeat #283540;
  background-size: 20px auto;
  background-position: 15px center;
};

.v-editor__sidepanel__item:nth-child(n+3) {
  background: url(/assets/@vtex.storefront-editor/icons/apps-icon.svg) no-repeat lighten(#283540, 5%);
  background-size: 20px auto;
  background-position: 15px center;
};

.v-editor__sidepanel__item:nth-child(n+4) {
  background: url(/assets/@vtex.storefront-editor/icons/pages-icon.svg) no-repeat lighten(#283540, 7.5%);
  background-size: 20px auto;
  background-position: 15px center;
};

.v-editor__sidepanel__item:nth-child(n+5) {
  background: url(/assets/@vtex.storefront-editor/icons/context-icon.svg) no-repeat lighten(#283540, 10%);
  background-size: 20px auto;
  background-position: 15px center;
};

.v-editor__sidepanel__item:nth-child(n+6) {
  background: url(/assets/@vtex.storefront-editor/icons/history-icon.svg) no-repeat lighten(#283540, 12.5%);
  background-size: 20px auto;
  background-position: 15px center;
};

```
